name: Update Data

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Data
      run: |
        # Use a script or a tool to fetch data from the API and save it as data.json
        # For example, using curl:
        curl -o data.json "https://newsapi.org/v2/everything?q=India&from=2023-08-27&sortBy=publishedAt&apiKey=f7ef6544496e4bb7bda0213af2821080"

    - name: Commit and Push Data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data.json
        git commit -m "Update data.json"
        git push

